# Site settings
title: CT101 - Lập trình căn bản
email: duongludientraining@gmail.com
description: "Học liệu và bài giảng cho khóa học CT101: Lập trình căn bản."
baseurl: ""
url: "http://ltcb.github.io"
twitter_username: duongludien
github_username:  ltcb

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

